### ISSUE TITLE
Bump libxmljs dep

### ISSUE THREAD

**Issue by wingrunr21** [strax/node-wolfram#16]
Per polotek/libxmljs#303, v0.13.0 has a build issue. v0.14.0 appears to build ok.

**Comment by dragonbanshee** [comment]
Yeah this needs to be updated. I'm not able to install this module because the libxmljs install fails, but I can install it by itself, just not with this version.

**Comment by wingrunr21** [comment]
@strax can you bump the version?

**Comment by strax** [comment]
@wingrunr21 Yeah sure, I'll try to find some time ASAP to do that.

**Comment by wingrunr21** [comment]
Awesome thanks

**Comment by strax** [comment]
Hi @wingrunr21, released version 0.3.2 that has the dependency bumped to 0.14.0.

**Comment by wingrunr21** [comment]
woo thanks!
