### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by shenkev** [strax/node-wolfram#20]
Hi,

I had no troubles installing on Ubuntu but it didn't go so smoothly on Windows powershell. There  seems to be an issue with Python version but also libxmljs?

gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\kevin\AppData\Local\Programs\Python\Python35-32\python.EXE" is v3.5.0,
 which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Program Files\nodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js
:454:14)
gyp ERR! stack     at D:\Program Files\nodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:486:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\Program Files\nodeJS\node.exe" "D:\Program Files\nodeJS\node_modules\npm\node_modules\node
-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Work\Equationary\node_modules\wolfram\node_modules\libxmljs
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\Program Files\nodeJS\node.exe" "D:\Program Files\nodeJS\node_modules\npm\bin\npm-cli.js" "ins
tall" "Wolfram"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

**Comment by strax** [comment]
@shenkev sorry for the delay. Did you manage to compile eventually?

**Comment by ItsDeadEnd** [comment]
npm needs python2 in order to run the script. it installed for me once i installed python2

**Comment by shenkev** [comment]
Sorry, I haven't tried this since posting the issue. We went with another solution.
