### ISSUE TITLE
Node.js API

### ISSUE THREAD

**Issue by AlaGarali** [strax/node-wolfram#24]
Hi,
I used this Node.js code:

[var http = require('http');
var createClient = require('./createClient');
//create a server object:
http.createServer(function (req, res) {
  res.write('Hello World!'); //write a response to the client 
var wolfram = require('wolfram').createClient("My ID");
var question = "how far nyc to chicago"
wolfram.query(question, function(err, result) {
    var results = result[1].subpods[0].value ;
    console.log("Result: %j", result[1].subpods[0].value) 
    res.write(results);
})  
    res.end(); //end the response
}).listen(8080);](url)

I have this error:
![erreur](https://user-images.githubusercontent.com/30980622/44080061-ca960c8e-9fa2-11e8-9a7b-b2bd2f2398ac.JPG)

I would like to store the result[1].subpods[0].value in a variable (results) so that I can display it on the html page (res.write) and also use it later.
How can I do this ?
Best regards.

**Comment by strax** [comment]
Hi, you seem to be close the stream (in `res.end`) before writing to it. This library fetches results asynchronously so the callback for `query` executes after you have ended the stream, hence the error. Try moving that `res.end()` line inside the callback.
